### ISSUE TITLE
[feat] Bypass need for PMU with itimer? 

### ISSUE THREAD

**Issue by dalehamel** [javierhonduco/rbperf#62] opened 2023-02-21 20:08 UTC
Currently we cannot use rbspy in many cases because we don't broadly have PMU access in GCP.

It looks like this is what fails:

https://github.com/javierhonduco/rbperf/blob/a6aac37715a1aabbbe84b7b4a72eb4d644214be2/src/events.rs#L49-L50

I notice that we are still able to run `async-profiler` for JVM profiling, because they add the option to support `itimer` as the clock source rather than perf:

https://github.com/async-profiler/async-profiler/blob/cdb87041561e0cf8b0597c3263eb3c09a3d49b5c/src/profiler.cpp#L882

I wonder if the same thing can be done with rbperf?

It looks like syscall profiling should still work without this and would be useful, but because of #61 I can't give that a go either

**Comment by dalehamel** [comment] 2023-02-22 04:06
Since the profiling is triggered by a hardware event, it might be more difficult to have it be triggered by a software event. 

Maybe it is possible to do something like set up itimer in userspace, and add a uprobe for when this itimer is triggered, but initiating it from another userspace process probably has pitfalls. I wonder if there is a software equivalent in perf...

For now though, it looks like there is a hard requirement on PMU access, which will make this trickier to run on some public clouds that don't provide access to it.

**Comment by javierhonduco** [comment] 2023-02-22 09:58
Hi Dale! 

Thanks for bringing this up, this is definitely something that should be fixed!

> Maybe it is possible to do something like set up itimer in userspace, and add a uprobe for when this itimer is triggered, but initiating it from another userspace process probably has pitfalls. I wonder if there is a software equivalent in perf...

As a last resort, we could do something like this but it shouldn't be necessary. The timing here is funny because I'm currently finishing a write-up on signal/itimer based profiling 😃.

> Since the profiling is triggered by a hardware event, it might be more difficult to have it be triggered by a software event.

`PERF_COUNT_SW_CPU_CLOCK` should work without PMU support I think and it's emulated by the kernel similarly to how itimer works underneath. Something that stands out is the `type` field. That's most definitely wrong!! Let me address it and hopefully this should unblock you

**Comment by javierhonduco** [comment] 2023-02-22 10:14
Oops, didn't intend to close this issue. Feel free to close once we verify this is fixed.

**Comment by javierhonduco** [comment] 2023-02-22 18:13
Dale, I assume this is sorted out now?

**Comment by dalehamel** [comment] 2023-02-22 18:16
sorry i'll give this a go after lunch, but in theory it should be - i thought there was a perf-based software timer just wasn't sure. If that's what you used i assume it solves it! I'll try it out on one of our clusters without PMU access to be completely sure 👍

**Comment by dalehamel** [comment] 2023-02-22 19:06
I can confirm on the latest master I can actually collect samples now 🎉 

Unfortunately I think we're seeing the same issue as in https://github.com/javierhonduco/rbperf/issues/61#issuecomment-1440434502

I see a lot of:

```
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=148 and received=129 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=145 and received=132 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=145 and received=132 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=145 and received=132 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=145 and received=132 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=145 and received=132 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=148 and received=129 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=148 and received=129 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=148 and received=129 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=176 and received=173 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=176 and received=170 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=184 and received=183 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=185 and received=184 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=185 and received=184 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=185 and received=184 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=224 and received=222 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=224 and received=222 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=224 and received=222 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=224 and received=222 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=234 and received=232 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=235 and received=233 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=234 and received=233 frame count
[2023-02-22T19:00:24Z ERROR rbperf::rbperf] mismatched expected=234 and received=233 frame count

```

I got a flame graph, but it is basically invalid because far more samples errored than were successful:

```
Got 10616 samples and 869805 errors
```

Though prior to your patch in #63, rbperf could not run at all so this is still progress, and if I understand that other issue, it is caused by hash collisions? This process is also a production rails process so it is pretty pathological in terms of stack depth etc (I've seen some callchains that are over 500 frames long!!!).

Anyways I think we consider this "Fixed", with a caveat being per my comment in https://github.com/javierhonduco/rbperf/pull/63#issuecomment-1440617379 we might want to either prefer hardware timing events if it is available, or make this an option to toggle between hardware / software clock source

**Comment by javierhonduco** [comment] 2023-02-23 10:31
> mismatched expected=185 and received=184 frame count

Uh, oh! That's an interesting exciting new error. Never seen it before! We can compute the expected stack frame size ahead of time. It's what we use to know when to stop unwinding the stack and we also use this in userspace to know whether stacks are truncated. This is the check that's failing.

Will look into it.

> Though prior to your patch in https://github.com/javierhonduco/rbperf/pull/63, rbperf could not run at all so this is still progress, and if I understand that other issue, it is caused by hash collisions? This process is also a production rails process so it is pretty pathological in terms of stack depth etc (I've seen some callchains that are over 500 frames long!!!).

Part of the problem is key/hash collisions, will hopefully get this improved in some days.

> This process is also a production rails process so it is pretty pathological in terms of stack depth etc (I've seen some callchains that are over 500 frames long!!!).

Woah! Glad that now rbperf bumped the max frames above that! 😄 

> Anyways I think we consider this "Fixed", with a caveat being per my comment in https://github.com/javierhonduco/rbperf/pull/63#issuecomment-1440617379 we might want to either prefer hardware timing events if it is available, or make this an option to toggle between hardware / software clock source

Sounds good! More than happy to accept a PR for this feature 😄

**Closed** 2023-02-23 10:32 UTC
